import = [
    "~/.config/alacritty/themes/themes/gruvbox_light.toml"
]
[env]
TERM = "xterm-245color"
[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 13
